### ISSUE TITLE
[help]Error Installing Gherkin

### ISSUE THREAD

**Issue by joefebrian** [cucumber-attic/gherkin2#139]
Hai, Everyone i'm can't handling this from my ubuntu 11.04, i stack everyone help me.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /home/joe/.rvm/rubies/ruby-1.9.2-p290/bin/ruby extconf.rb 
```

checking for main() in -lc... yes
creating Makefile

make
gcc -I. -I/home/joe/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/i686-linux -I/home/joe/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1/ruby/backward -I/home/joe/.rvm/rubies/ruby-1.9.2-p290/include/ruby-1.9.1 -I. -D_FILE_OFFSET_BITS=64  -fPIC -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wno-long-long  -fPIC -O0 -Wall -Werror  -o gherkin_lexer_ar.o -c gherkin_lexer_ar.c
/Users/aslakhellesoy/scm/gherkin/tasks/../ragel/i18n/ar.c.rl: In function ‘CLexer_scan’:
/Users/aslakhellesoy/scm/gherkin/tasks/../ragel/i18n/ar.c.rl:199:29: error: the comparison will always evaluate as ‘true’ for the address of ‘raise_lexer_error’ will never be NULL [-Werror=address]
/Users/aslakhellesoy/scm/gherkin/tasks/../ragel/i18n/ar.c.rl:199:29: error: the comparison will always evaluate as ‘true’ for the address of ‘raise_lexer_error’ will never be NULL [-Werror=address]
cc1: all warnings being treated as errors

make: **\* [gherkin_lexer_ar.o] Error 1

Gem files will remain installed in /home/joe/.rvm/gems/ruby-1.9.2-p290@rails311/gems/gherkin-2.2.9 for inspection.
Results logged to /home/joe/.rvm/gems/ruby-1.9.2-p290@rails311/gems/gherkin-2.2.9/ext/gherkin_lexer_ar/gem_make.out
An error occured while installing gherkin (2.2.9), and Bundler cannot continue.

**Comment by rahulv2** [comment]
sadas

**Comment by rahulv2** [comment]
sdfsdf
