### ISSUE TITLE
Gherkin Json formatter does not include a result for scenario outlines

### ISSUE THREAD

**Issue by josephwilk** [cucumber-attic/gherkin2#165]
Gherkin 2.9.0. 
I'll add some concrete examples to this but I suspect that the JSON formatter does not output the result for scenario outlines.

For scenarios we get:

<pre>
{"steps"=>[{"result"=>{"status"=>"passed"}, .....,  "type"=>"scenario", "description"=>"", "keyword"=>"Scenario"}
</pre>

Where result indicates the step passed.

For scenario outlines:

<pre>
{"examples"=>[{"name"=>"", "line"=>114}], ....}
</pre>

There is nothing about the status of the examples/rows/cells.

**Comment by philchen00** [comment]
Is there a javascript version of this fix as well?
