### ISSUE TITLE
Unable to Install gherkin using gem install

### ISSUE THREAD

**Issue by andiputra** [cucumber-attic/gherkin2#168]
I encountered the error below when trying to install gherkin to be used together with cucumber. I'm not sure what is wrong. I remember I did install cucumber once on my Snow Leopard. I'm currently using Lion and have XCode 4.3.1 installed, could this cause the problem? Anyway, thanks for the help.

Building native extensions.  This could take a while...
ERROR:  Error installing gherkin:
    ERROR: Failed to build gem native extension.

/Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/bin/ruby extconf.rb
checking for main() in -lc... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/bin/ruby
    --with-gherkin_lexer_ar-dir
    --without-gherkin_lexer_ar-dir
    --with-gherkin_lexer_ar-include
    --without-gherkin_lexer_ar-include=${gherkin_lexer_ar-dir}/include
    --with-gherkin_lexer_ar-lib
    --without-gherkin_lexer_ar-lib=${gherkin_lexer_ar-dir}/lib
    --with-clib
    --without-clib
/Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:368:in `try_do': The complier failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:435:in`try_link0'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:440:in `try_link'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:552:in`try_func'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:748:in `block in have_library'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:693:in`block in checking_for'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:280:in `block (2 levels) in postpone'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:254:in`open'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:280:in `block in postpone'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:254:in`open'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:276:in `postpone'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:692:in`checking_for'
    from /Users/andiputra7/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/mkmf.rb:743:in `have_library'
    from extconf.rb:5:in`<main>'

Gem files will remain installed in /Users/andiputra7/.rvm/gems/ruby-1.9.2-p290/gems/gherkin-2.9.0 for inspection.
Results logged to /Users/andiputra7/.rvm/gems/ruby-1.9.2-p290/gems/gherkin-2.9.0/ext/gherkin_lexer_ar/gem_make.out

**Comment by anthonygreen** [comment]
I'm getting this error with Debian Jessie as well.
